rtl/packages/soc_pkg.sv
rtl/packages/reg_pkg.sv
rtl/packages/accel_pkg.sv
rtl/interfaces/axil_if.sv
rtl/interfaces/mem_if.sv
rtl/interfaces/stream_if.sv
rtl/interfaces/irq_if.sv
rtl/interfaces/cmd_if.sv
rtl/common/skid_buffer.sv
rtl/fifo/sync_fifo.sv
rtl/memory/simple_dual_port_ram.sv
rtl/memory/scratchpad_ram.sv
rtl/memory/soc_memory_fabric.sv
rtl/regs/soc_register_block.sv
rtl/dma/dma_engine.sv
rtl/dma/dma_command_adapter.sv
rtl/timer/soc_timer.sv
rtl/irq/irq_controller.sv
rtl/perf/performance_counters.sv
rtl/command_queue/command_queue.sv
rtl/command_queue/command_processor.sv
rtl/accel/vector_alu/vector_accelerator.sv
rtl/accel/reduction/reduction_accelerator.sv
rtl/accel/gemm/gemm_accelerator.sv
rtl/soc/soc_top.sv
