+incdir+uvm/agents/axil_agent
+incdir+uvm/agents/mem_agent
+incdir+uvm/agents/irq_agent
+incdir+uvm/agents/cmd_agent
+incdir+uvm/env
+incdir+uvm/sequences
+incdir+uvm/scoreboards
+incdir+uvm/coverage
+incdir+uvm/tests
uvm/interfaces/soc_irq_if.sv
uvm/interfaces/soc_reset_if.sv
uvm/interfaces/soc_command_monitor_if.sv
uvm/packages/axil_agent_pkg.sv
uvm/packages/mem_agent_pkg.sv
uvm/packages/irq_agent_pkg.sv
uvm/packages/cmd_agent_pkg.sv
uvm/packages/soc_uvm_pkg.sv
uvm/assertions/soc_top_assertions.sv
sim/uvm/tb_top.sv
